# Generated by Django 2.0.2 on 2020-11-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_journal', '0002_auto_20201127_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
